# fly.toml app configuration file generated for unknowndefault on 2023-11-10T11:22:16+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unknowndefault"
primary_region = "sin"
swap_size_mb = 1024

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
